apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infrastructure/k8s/*
build:
  googleCloudBuild:
    projectId: hybrid-essence-451723-a3
  artifacts:
    - image: us.gcr.io/hybrid-essence-451723-a3/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
