name: deploy-manifests

on:
  push:
    branches:
      - develop
    paths:
      - "infrastructure/**"

jobs:
  build:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - name: Init Ticketing Cluster
        run: doctl kubernetes cluster kubeconfig save ticketing
      - name: Apply Infrastrcture K8s
        run: kubectl apply -f infrastructure/k8s && kubectl apply -f infrastructure/k8s-prod
