name: deploy-payments

on:
  push:
    branches:
      - develop
    paths:
      - "payments/**"

jobs:
  build:
    name: Deploy payments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to Docker
        run: |
          cd payments
          npm run build
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          npm run push
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - name: Init Ticketing Kube
        run: doctl kubernetes cluster kubeconfig save ticketing
      - name: Rollout Payments Deployment
        run: kubectl rollout restart deployment payments-depl
