name: test-orders

on:
  pull_request:
    paths:
      - "orders/**"

jobs:
  build:
    name: Test orders
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd orders && npm ci && npm run test:ci
