name: test-tickets

on:
  pull_request:
    paths:
      - "tickets/**"

jobs:
  build:
    name: Test tickets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd tickets && npm ci && npm run test:ci
